### ISSUE TITLE
Timeout when attempting to add songs from Spotify playlist to mopidy playlist

### ISSUE THREAD

**Issue by johnhamelink** [trygveaa/mopidy-spotify-tunigo#9]
Hey there,

When I browse through the playlists that `mopidy-spotify-tunigo` provides for me and attempt to append them to my mopidy playlist, I get the following stacktrace in mopidy:

```
ERROR    SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 142, in get_distinct
    values = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/library.py", line 26, in get_distinct
    field, query)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 20, in get_distinct
    config, session, web_client, query)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 45, in _get_distinct_artists
    for track in _get_playlist_tracks(config, session)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 44, in <setcomp>
    artist.name
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 119, in _get_playlist_tracks
    playlist.load(config['timeout'])
  File "/usr/lib/python2.7/site-packages/spotify/playlist.py", line 118, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by en00x** [comment]
+1

**Comment by trygveaa** [comment]
Sorry for never answering here. I think this was caused by an issue in mopidy-spotify where playlists could not be loaded (or really an issue in the underlying libspotify library). This has just been fixed, but unfortunately, the Tunigo service has shut down in the mean time. [The Spotify Web API](https://developer.spotify.com/documentation/web-api/) has support for some or all of the functionality this extension provided, so that might be added to [Mopidy-Spotify](https://github.com/mopidy/mopidy-spotify) in the future.
